version: '3.8'
services:
  back:
    container_name: titiback
    build:
      context: ./back/
      target: production
      # network: host
    command: pm2-runtime dist/index.js
    ports:
      - "5000:5000"
    networks:
      - titinetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  titinetwork:
    name: titinetwork
